### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by PabloDevGit** [Ragath/Tyxel#1]
Hello, please do not understand very well how to use it.
I have to save the pyxel file and then what do I do ?.

The included sample works but with my pyxel file it does not work.

**Comment by Ragath** [comment]
Pyxel got updated to a new version a few days ago, i suspect the format might have changed and thats why you're having issues. I've been meaning to take a look at the new format but unfortunately haven't gotten around to it yet.

**Comment by Ragath** [comment]
@Torguen I have now verified that the current pyxel version(v0.4.4) still works.  
The Tyxel sample works like this:

- Sample.json defines the conversion settings(such as which .pyxel file to observe and the name of the tileset to generate).
- You open this file using Tyxel.exe(possibly by dropping Sample.json on it) in order to start observing.

I will update the readme to make this more clear.
Edit: planning to make this process more intuitive by implementing #2
